# Generated by Django 3.2.9 on 2021-11-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('anneEtude', models.PositiveIntegerField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Storage/Images')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firt_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('Birthday', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Storage/Images')),
            ],
        ),
        migrations.CreateModel(
            name='rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('text', models.CharField(max_length=50)),
                ('problems', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('idChild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToysStore.child')),
                ('idRapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ToysStore.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('attitude', models.FloatField(blank=True)),
                ('ChildPlaces', models.ManyToManyField(to='ToysStore.Child')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='idParent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToysStore.parent'),
        ),
    ]
