# Generated by Django 3.2.9 on 2021-11-24 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ToysStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='benefice',
            field=models.CharField(default='dfdfefefe', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='anneEtude',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='child',
            name='photo',
            field=models.ImageField(upload_to='Storage/Images'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='Birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='photo',
            field=models.ImageField(upload_to='Storage/Images'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateDebut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='dateFin',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=50)),
                ('date_message', models.DateField()),
                ('idChild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToysStore.child')),
            ],
        ),
        migrations.CreateModel(
            name='emplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100)),
                ('remarque', models.CharField(max_length=50)),
                ('empChild', models.ManyToManyField(to='ToysStore.Child')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='idEmplacement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ToysStore.emplacement'),
            preserve_default=False,
        ),
    ]
